# Generated by Django 5.0.6 on 2024-07-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='num_of_items',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_in_stock',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
